# Base configs
baseurl: " https://lav30.github.io/photography/."
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "My Portfolio"
subtitle: "Welcome to my Page"
author: "Lavanya"
bio: "Engineer, Seeker, Artist"
social_urls:
  github: "https://www.github.com/lav30"
  

theme: jekyll-theme-midnight