# Base configs
baseurl: " https://lav30.github.io/photography/."
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "My Photography"
author: "Lavanya"
header:
 title: "Photography"
 subtitle: "by Lavanya"
web_design: "AJ"
social_urls:
  github: "https://www.github.com/lav30"
